In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({
    'column_a':[1,2,3,4],
    'column_b':['a','b','c','d'],
    'column_c':[True,True,False,False]
})
df1

   column_a column_b  column_c
0         1        a      True
1         2        b      True
2         3        c     False
3         4        d     False

In [4]:
df2 = pd.DataFrame({
    'column_a':[4,7,3,4],
    'column_b':['U','G','E','d'],
    'column_c':[False,False,True,True]
})
df2

   column_a column_b  column_c
0         4        U     False
1         7        G     False
2         3        E      True
3         4        d      True

In [8]:
df = pd.concat([df1,df2])
df

   column_a column_b  column_c
0         1        a      True
1         2        b      True
2         3        c     False
3         4        d     False
0         4        U     False
1         7        G     False
2         3        E      True
3         4        d      True

In [10]:
df = pd.concat([df1,df2], keys=['df1','df2'])
df

       column_a column_b  column_c
df1 0         1        a      True
    1         2        b      True
    2         3        c     False
    3         4        d     False
df2 0         4        U     False
    1         7        G     False
    2         3        E      True
    3         4        d      True

In [5]:
df = pd.concat([df1,df2], ignore_index=True)
df

   column_a column_b  column_c
0         1        a      True
1         2        b      True
2         3        c     False
3         4        d     False
4         4        U     False
5         7        G     False
6         3        E      True
7         4        d      True

In [6]:
df = pd.concat([df1,df2], axis=1)
df

   column_a column_b  column_c  column_a column_b  column_c
0         1        a      True         4        U     False
1         2        b      True         7        G     False
2         3        c     False         3        E      True
3         4        d     False         4        d      True

In [7]:
df1

   column_a column_b  column_c
0         1        a      True
1         2        b      True
2         3        c     False
3         4        d     False

In [8]:
df2

   column_a column_b  column_c
0         4        U     False
1         7        G     False
2         3        E      True
3         4        d      True

In [10]:
df_merge = pd.merge(df1,df2)
df_merge

Empty DataFrame
Columns: [column_a, column_b, column_c]
Index: []

In [11]:
df_merge = pd.merge(df1,df2, on='column_a')
df_merge

   column_a column_b_x  column_c_x column_b_y  column_c_y
0         3          c       False          E        True
1         4          d       False          U       False
2         4          d       False          d        True

In [7]:
df2.rename(columns={'column_a':'new_column_a'},inplace=True)
df2

   new_column_a column_b  column_c
0             4        U     False
1             7        G     False
2             3        E      True
3             4        d      True

In [8]:
df_merge = pd.merge(df1,df2, left_on='column_a',right_on='new_column_a')
df_merge

   column_a column_b_x  column_c_x  new_column_a column_b_y  column_c_y
0         3          c       False             3          E        True
1         4          d       False             4          U       False
2         4          d       False             4          d        True