In [1]:
import pandas as pd
df= pd.read_csv("Students_exams.csv")
df

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [2]:
x= df.std(numeric_only=True)
x

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

In [3]:
x= df.mode()
x

   gender  math score  reading score  writing score
0  female          65             72             74